name: Update file of namespaces used by each configuration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-namespaces:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate a Neurobagel Bot token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.NB_BOT_ID }}
          private-key: ${{ secrets.NB_BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to update namespaces
        run: python code/create_config_namespace_map.py

      - name: Get Neurobagel Bot App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Configure git for Neurobagel Bot user
        run: |
          git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add config_metadata/config_namespace_map.json
          git commit -m "[bot] Update config_namespace_map.json" || true
          git push origin main
